require('dotenv').config()
const fs = require('fs');
const swaggerAutogen = require('swagger-autogen')({openapi: '3.1.0', autoBody: true})

const outputFile = './swagger_output.json'
const endpointsFiles = ['./route/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Nusablockchain Api Backend",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    servers: [
        {
          url: `http://localhost:${process.env.PORT}/api`,
          description: "development"
        },
        {
          url: `${process.env.APP_URL}/api`,
          description: "production"
        }
    ],
    securityDefinitions: {
      Bearer: {
        type: "apiKey",
        name: "token",
        in: "header",
      }
    },
    basePath: "/api/",
    consumes: ['application/json'],
    produces: ['application/json'],
    components: require('./config/dto/definitions.json')
}

swaggerAutogen(outputFile, endpointsFiles, doc)