require('dotenv').config()
const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0',autoHeaders: true})

const outputFile = './swagger_output.json'
const endpointsFiles = ['./route/index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Nusablockchain Api Backend",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    servers: [
        {
          url: `http://localhost:${process.env.PORT}/api`,
          description: "development"
        },
        {
          url: `${process.env.APP_URL}/api`,
          description: "production"
        }
    ],
    definitions: {
      Login: {
          email: "example@example.com",
          password: "Example123!*",
      },
      AddUser: {
          $name: "example@example.com",
          $age: "Example123!*",
      }
    },
    basePath: "/api/",
    consumes: ['application/json'],
    produces: ['application/json'],
}

swaggerAutogen(outputFile, endpointsFiles, doc)